In [1]:
import numpy as np

### Approximate Matching

In [2]:
def matrix_edit_distance(x, y):
    D = np.zeros((len(x)+1, len(y)+1), dtype=int)
    D[:,0] = range(len(x)+1)
    for i in range(1, len(x)+1):
        for j in range(1, len(y)+1):
            delta = 1 if x[i-1] != y[j-1] else 0
            D[i, j] = min((D[i-1, j-1] + delta), 
                          (D[i, j-1] + 1), 
                          (D[i-1,j] + 1))
    return D

In [3]:
x = 'GCGTATGC'
y = 'TATTGGCTATACGGTT'
D = matrix_edit_distance(x, y)
print D

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 1 1]
 [2 2 2 2 2 1 1 0 1 2 2 2 1 1 1 1 2]
 [3 3 3 3 3 2 1 1 1 2 3 3 2 1 1 2 2]
 [4 3 4 3 3 3 2 2 1 2 2 3 3 2 2 1 2]
 [5 4 3 4 4 4 3 3 2 1 2 2 3 3 3 2 2]
 [6 5 4 3 4 5 4 4 3 2 1 2 3 4 4 3 2]
 [7 6 5 4 4 4 5 5 4 3 2 2 3 3 4 4 3]
 [8 7 6 5 5 5 5 5 5 4 3 3 2 3 4 5 4]]


In [10]:
def trace_back(x, y, D):
    align_x = list()
    align_y = list()
    i = len(x)
    min_ = min(D[i,:])
    j = np.argmin(D[i,:], axis=0)
    align_x = list()
    align_y = list()
    while i > 0:
        diagonal = D[i-1, j-1]
        vertical = D[i-1, j]
        horizontal = D[i, j-1]
        min_ = min(diagonal, vertical, horizontal)
        if min_ == diagonal:
            align_x.append(x[i-1])
            align_y.append(y[j-1])
            i -= 1
            j -= 1
        elif min_ == vertical:
            align_x.append('-')
            align_y.append(y[j-1])
            j -= 1
        elif min_ == horizontal:
            align_y.append('-')
            align_x.append(x[i-1])
            i -= 1
    return ''.join(align_x)[::-1], ''.join(align_y)[::-1]
    

In [11]:
align_x, align_y = trace_back(x, y, D)

In [12]:
align_x

'GC-G-TATGC'

In [13]:
align_y

'TTGGCTATAC'